### ISSUE TITLE
Issues on Samsung mobiles

### ISSUE THREAD

**Issue by mrfcoelho** [AR-js-org/locar.js#3]
hi, I was trying the example "02-gps-and-sensors" on a samsung A15 and I get a black background, instead of seeing the room where I'm at. I see the boxes around, but with a black background.

Alos, I tried the same example on a samsung A25 5G, and the screen gets black and nothing happens (no boxes nor the initial message with my gps coordinates). Both devices have the same Chrome version (131.0.6.6778.135) and the same OS version (android 14).

Can you help me understand what am I missing herein?

**Comment by nickw1** [comment]
@mrfcoelho I have now updated locar.js to display an alert if there are errors connecting to the camera. I have also included more information in the console log.

For both devices, update locar.js to 0.0.3 (the latest commit) and ensure 0.0.3 is being used. If there is an error connecting to the camera, an alert box should appear.

For the A25 5G, try running the example through remote debugging with your device connected, and inspect the console to see what messages appear. If a new GPS location is obtained this should be displayed on the console. Does anything appear?

https://developer.chrome.com/docs/devtools/remote-debugging

I presume other location-based apps work on the A25 5G?

**Comment by mrfcoelho** [comment]
Hi @nickw1,
Thanks for the quick reply and excuse me for the delayed answer. Answers below:

**Just to check - I presume you are not running another app on the device which uses the camera at the same time you are trying to use locar.js?** Yes, I'm only running chrome at the time I'm testing and facing the reported issue.

**I presume other location-based apps work on the A25 5G?** You may have made a point here. I tried google maps app and verified it was taking too much time to find directions to a location I've picked. After restarting the phone, everything started working fine, including the examples I was reporting initialy. That said, I believe this issue can be closed as the problem was on my phone.

Nevertheless, I tried what you suggested, so I'll report below what I was getting:
This was on the A15, where it was working perfectly since beggining:
![A15](https://github.com/user-attachments/assets/edf18a37-0395-42dc-832e-e9b64c2b6f33)

This was on the A25 before the restart that apparently fixed everything:
![A25](https://github.com/user-attachments/assets/665a4488-0115-4ea7-8147-cc73c3dfdd8d)

Btw, what does the accuracy parameter represent? I was looking into the code but was unable to figure it out.

Thanks!

**Comment by kalwalt** [comment]
Hi @mrfcoelho, i'm not the guru here but i think the printing message should come from: https://github.com/AR-js-org/locar.js/blob/fffc1e7f899a79b620095c54323589ec1d1c48ac/lib/src/location-based.js#L116 
You can find the accuracy parameter in the constructor of the class. It is required because the retrieved Lat Long coords from `navigator.geolocation` add this [option](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/accuracy). It's reccomended a reading of [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API) 🙂

**Comment by nickw1** [comment]
Hi @mrfcoelho, great. To add to @kalwalt's comments, the accuracy is the minimum accuracy in metres for the GPS position to be accepted. So if the minimum accuracy is 10m, only GPS fixes with an accuracy of 10m or less (i.e. a point which is accurate to within 10m or less) will be accepted, and any GPS position received with an accuracy of greater than 10m will be ignored.

In your case the accuracy limit is 100m and your GPS points are to within 12m so they will be accepted.

I will close the issue now but if problems recur feel free to reopen.
